- name: run test Elixir nodes
  docker_container:
    network_mode: "{{network}}"
    name: "{{elixir_container_name}}{{ item }}"
    hostname: elixir{{ item | regex_replace('^[0-9]\.') }}
    image: "{{ custom_elixir_docker_image if ( item in elixir_customized_versions ) else elixir_docker_image }}{{item}}"
    container_default_behavior: no_defaults
    command: sh -c "elixir --sname test"{{ item | regex_replace('^[0-9]\.')  }}"  --cookie "{{cookie}}" --no-halt && ps aux | grep elixir"
    mounts:
      - source: /Users/wisamdsh/wombat-agents-test/scripts
        target: /wombat/ansible/scripts
        type: bind
  with_items: "{{elixir_customized_versions}} + {{elixir_versions}}"



