---     
- hosts: local
  vars_files:
    - external-vars.yaml
  roles:
    - {role: docker, action: "ensure_docker"}
    - {role: docker, action: "clean_containers"} 
    - {role: erlang, action: "build_custom_images"}
    - {role: wombat, action: "start_wombat_container"}
    - {role: erlang, action: "start_nodes"}
    - {role: wombat, action: "prepare_wombat", delegate_to: ans-wombat}
    - {role: docker, action: "get_nodes_names", product: "erlang"}
    - {role: wombat, action: "add_nodes", delegate_to: ans-wombat}
  
- hosts: erlang_inv
  vars: 
    nodes_names: "{{ hostvars['localhost']['ansible_facts']['nodes_names'] }}"
  roles:
    - {role: check_agents}
    - {role: check_metrics}


    

- hosts: local
  tasks:

    - name: debug hostvars
      debug: 
        var: hostvars["ans-erlang17"]


    - name: Generate Erlang report
      template:
        src: /Users/wisamdsh/wombat-agents-test/report_template.j2
        dest: /Users/wisamdsh/ans-reports/erlang.html
      vars:
        inventories: 'erlang_inv'
...