---     
- hosts: local
  vars_files:
    - external-vars.yaml
  roles:
    - {role: docker, action: "ensure_docker"}
    - {role: rmq, action: "build_custom_images"}
    - {role: rmq, action: "test_rmq"}
  

# - hosts: rmq_inv
#   tasks:
#     - name: nothing
#       debug:
#         msg: "just to gather the facts"
# - hosts: local
#   tasks:
    

#     - name: debug hostvars
#       debug: 
#         var: hostvars["localhost"]
    
# - hosts: rmq_inv
#   tasks:
#     - name: install python3
#       command: sh -c "apt-get update && apt-get install python3"
  # roles:
    # - roles/rmq/tasks/ensure_rmq_running.yml