- hosts: local
  vars_files:
    - external-vars.yaml
  roles:
    - {role: docker, action: "ensure_docker"}
    - {role: docker, action: "clean_containers"} 


- hosts: local
  vars:
    variable_to_be_replaced: 'Hello world'
    inline_variable: 'hello again'
  tasks:
    - name: Ansible Template Example
      template:
        src: /Users/wisamdsh/wombat-agents-test/report_template.j2
        dest: /Users/wisamdsh/ans-reports/erlang.html