- name: run test Erlang node
  docker_container:
    network_mode: "{{network}}"
    name: "{{erlang_container_name}}{{ item }}"
    hostname: erlang{{ item }}
    image: "{{ custom_erlang_docker_image if ( item in erlang_customized_versions ) else erlang_docker_image }}{{item}}"
    container_default_behavior: no_defaults
    command: sh -c "erl -noshell -sname test"{{ item }}" -setcookie "{{cookie}}""
    mounts:
      - source: ../../../scripts
        target: /wombat/ansible/scripts
        type: bind
  with_items: "{{erlang_customized_versions}} + {{erlang_versions}} "