
- name: clean containers
  import_role:
    name: docker
    tasks_from: tasks/clean_containers.yml

- name: start wombat
  import_role: 
    name: wombat
    tasks_from: tasks/start_wombat_container.yml

- name: run rmq node
  import_role:
    name: rmq
    tasks_from: tasks/start_rmq.yml

- name: check if RabbitMQ has started
  import_role: 
    name: rmq 
    tasks_from: tasks/ensure_rmq_running.yml
  delegate_to: "{{version}}"

- name: set admin user 
  import_role: 
    name: rmq
    tasks_from: tasks/set_user.yml
  delegate_to: "{{version}}"

- name: start perftest
  import_role:
    name: rmq
    tasks_from: tasks/run_perftest.yml

- name: prepare_wombat
  import_role:
    name: wombat
    tasks_from: tasks/prepare_wombat.yml
  delegate_to: ans-wombat

- name: get running nodes' names to add to wombat
  import_role:
    name: docker 
    tasks_from: tasks/get_nodes_names.yml
  vars:
    product: "rmq"
  

- name: add nodes to wombat
  import_role:
    name: wombat
    tasks_from: tasks/add_nodes.yml
  delegate_to: ans-wombat

- name: check the agents
  import_role:
    name: check_agents
  delegate_to: "{{version}}"

- name: check the metrics
  import_role:
    name: check_metrics
  delegate_to: "{{version}}"

- name: collect results
  set_fact: 
    scripts_results: "{{ scripts_results | default({}) | combine ({ version : {'agents': agents_script_result.stdout, 'metrics': metrics_script_result.stdout}}) }}"