

- name: run RMQ node
  docker_container:
    network_mode: "{{network}}"
    name: "{{rmq_container_name}}{{release}}"
    hostname: rmq
    image: "{{docker_image}}{{release}}-management"
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672
    container_default_behavior: no_defaults
    # command: sh -c "rabbitmq-server"
    mounts:
      - source: "{{playbook_dir}}/scripts"
        target: /wombat/ansible/scripts
        type: bind
      - source: "{{playbook_dir}}/rmq/enabled_plugins"
        target: /etc/rabbitmq/enabled_plugins
        type: bind
      - source: "{{playbook_dir}}/rmq/erlang.cookie"
        target: /root/.erlang.cookie
        type: bind
      - source: "{{playbook_dir}}/rmq/erlang.cookie"
        target: /var/lib/rabbitmq/.erlang.cookie
        type: bind



